alpha = 1.0
disabledAlpha = 0.6
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = [229, 229, 229, 1.0]
TextDisabled = [153, 153, 153, 1.0]
WindowBg = [0, 0, 0, 0.85]
ChildBg = [0, 0, 0, 0.0]
PopupBg = [28, 28, 35, 0.92]
Border = [127, 127, 127, 0.5]
BorderShadow = [0, 0, 0, 0.0]
FrameBg = [109, 109, 109, 0.39]
FrameBgHovered = [119, 119, 175, 0.4]
FrameBgActive = [107, 104, 163, 0.69]
TitleBg = [68, 68, 137, 0.83]
TitleBgActive = [81, 81, 160, 0.87]
TitleBgCollapsed = [102, 102, 204, 0.2]
MenuBarBg = [102, 102, 140, 0.8]
ScrollbarBg = [51, 63, 76, 0.6]
ScrollbarGrab = [102, 102, 204, 0.3]
ScrollbarGrabHovered = [102, 102, 204, 0.4]
ScrollbarGrabActive = [104, 99, 204, 0.6]
CheckMark = [66, 150, 250, 1.0]
SliderGrab = [61, 133, 224, 1.0]
SliderGrabActive = [66, 150, 250, 1.0]
Button = [89, 102, 155, 0.62]
ButtonHovered = [102, 122, 181, 0.79]
ButtonActive = [117, 137, 204, 1.0]
Header = [102, 102, 229, 0.45]
HeaderHovered = [114, 114, 229, 0.8]
HeaderActive = [135, 135, 221, 0.8]
Separator = [127, 127, 127, 0.6]
SeparatorHovered = [153, 153, 178, 1.0]
SeparatorActive = [178, 178, 229, 1.0]
ResizeGrip = [255, 255, 255, 0.1]
ResizeGripHovered = [198, 209, 255, 0.6]
ResizeGripActive = [198, 209, 255, 0.9]
Tab = [85, 85, 174, 0.786]
TabHovered = [114, 114, 229, 0.8]
TabActive = [103, 103, 185, 0.842]
TabUnfocused = [72, 72, 145, 0.8212]
TabUnfocusedActive = [89, 89, 166, 0.8372]
PlotLines = [255, 255, 255, 1.0]
PlotLinesHovered = [229, 178, 0, 1.0]
PlotHistogram = [229, 178, 0, 1.0]
PlotHistogramHovered = [255, 153, 0, 1.0]
TableHeaderBg = [68, 68, 96, 1.0]
TableBorderStrong = [79, 79, 114, 1.0]
TableBorderLight = [66, 66, 71, 1.0]
TableRowBg = [0, 0, 0, 0.0]
TableRowBgAlt = [255, 255, 255, 0.07]
TextSelectedBg = [0, 0, 255, 0.35]
DragDropTarget = [255, 255, 0, 0.9]
NavHighlight = [114, 114, 229, 0.8]
NavWindowingHighlight = [255, 255, 255, 0.7]
NavWindowingDimBg = [204, 204, 204, 0.2]
ModalWindowDimBg = [51, 51, 51, 0.35]
