alpha = 1.0
disabledAlpha = 0.6
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = [255, 255, 255, 1.0]
TextDisabled = [127, 127, 127, 1.0]
WindowBg = [15, 15, 15, 0.94]
ChildBg = [0, 0, 0, 0.0]
PopupBg = [20, 20, 20, 0.94]
Border = [109, 109, 127, 0.5]
BorderShadow = [0, 0, 0, 0.0]
FrameBg = [40, 73, 122, 0.54]
FrameBgHovered = [66, 150, 249, 0.4]
FrameBgActive = [66, 150, 249, 0.67]
TitleBg = [10, 10, 10, 1.0]
TitleBgActive = [40, 73, 122, 1.0]
TitleBgCollapsed = [0, 0, 0, 0.51]
MenuBarBg = [35, 35, 35, 1.0]
ScrollbarBg = [5, 5, 5, 0.53]
ScrollbarGrab = [79, 79, 79, 1.0]
ScrollbarGrabHovered = [104, 104, 104, 1.0]
ScrollbarGrabActive = [130, 130, 130, 1.0]
CheckMark = [66, 150, 250, 1.0]
SliderGrab = [61, 133, 224, 1.0]
SliderGrabActive = [66, 150, 250, 1.0]
Button = [66, 150, 249, 0.4]
ButtonHovered = [66, 150, 249, 1.0]
ButtonActive = [15, 135, 249, 1.0]
Header = [66, 150, 249, 0.31]
HeaderHovered = [66, 150, 249, 0.8]
HeaderActive = [66, 150, 249, 1.0]
Separator = [109, 109, 127, 0.5]
SeparatorHovered = [25, 102, 191, 0.78]
SeparatorActive = [25, 102, 191, 1.0]
ResizeGrip = [66, 150, 249, 0.2]
ResizeGripHovered = [66, 150, 249, 0.67]
ResizeGripActive = [66, 150, 249, 0.95]
Tab = [45, 89, 147, 0.862]
TabHovered = [66, 150, 249, 0.8]
TabActive = [50, 104, 173, 1.0]
TabUnfocused = [17, 26, 37, 0.9724]
TabUnfocusedActive = [34, 66, 108, 1.0]
DockingPreview = [66, 150, 250, 0.7]
DockingEmptyBg = [51, 51, 51, 1.0]
PlotLines = [155, 155, 155, 1.0]
PlotLinesHovered = [255, 109, 89, 1.0]
PlotHistogram = [229, 178, 0, 1.0]
PlotHistogramHovered = [255, 153, 0, 1.0]
TableHeaderBg = [48, 48, 51, 1.0]
TableBorderStrong = [79, 79, 89, 1.0]
TableBorderLight = [58, 58, 63, 1.0]
TableRowBg = [0, 0, 0, 0.0]
TableRowBgAlt = [255, 255, 255, 0.06]
TextSelectedBg = [66, 150, 249, 0.35]
DragDropTarget = [255, 255, 0, 0.9]
NavHighlight = [66, 150, 249, 1.0]
NavWindowingHighlight = [255, 255, 255, 0.7]
NavWindowingDimBg = [204, 204, 204, 0.2]
ModalWindowDimBg = [204, 204, 204, 0.35]
