alpha = 1.0
disabledAlpha = 0.6
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = [0, 0, 0, 1.0]
TextDisabled = [153, 153, 153, 1.0]
WindowBg = [239, 239, 239, 1.0]
ChildBg = [0, 0, 0, 0.0]
PopupBg = [255, 255, 255, 0.98]
Border = [0, 0, 0, 0.3]
BorderShadow = [0, 0, 0, 0.0]
FrameBg = [255, 255, 255, 1.0]
FrameBgHovered = [66, 150, 249, 0.4]
FrameBgActive = [66, 150, 249, 0.67]
TitleBg = [244, 244, 244, 1.0]
TitleBgActive = [209, 209, 209, 1.0]
TitleBgCollapsed = [255, 255, 255, 0.51]
MenuBarBg = [219, 219, 219, 1.0]
ScrollbarBg = [249, 249, 249, 0.53]
ScrollbarGrab = [175, 175, 175, 0.8]
ScrollbarGrabHovered = [124, 124, 124, 0.8]
ScrollbarGrabActive = [124, 124, 124, 1.0]
CheckMark = [66, 150, 250, 1.0]
SliderGrab = [61, 133, 224, 1.0]
SliderGrabActive = [66, 150, 250, 1.0]
Button = [66, 150, 249, 0.4]
ButtonHovered = [66, 150, 249, 1.0]
ButtonActive = [15, 135, 249, 1.0]
Header = [66, 150, 249, 0.31]
HeaderHovered = [66, 150, 249, 0.8]
HeaderActive = [66, 150, 249, 1.0]
Separator = [99, 99, 99, 0.62]
SeparatorHovered = [35, 112, 204, 0.78]
SeparatorActive = [35, 112, 204, 1.0]
ResizeGrip = [89, 89, 89, 0.17]
ResizeGripHovered = [66, 150, 249, 0.67]
ResizeGripActive = [66, 150, 249, 0.95]
Tab = [194, 203, 213, 0.931]
TabHovered = [66, 150, 249, 0.8]
TabActive = [151, 185, 225, 1.0]
TabUnfocused = [234, 236, 238, 0.9862]
TabUnfocusedActive = [189, 209, 233, 1.0]
DockingPreview = [66, 150, 250, 0.7]
DockingEmptyBg = [225, 225, 225, 1.0]
PlotLines = [99, 99, 99, 1.0]
PlotLinesHovered = [255, 109, 89, 1.0]
PlotHistogram = [229, 178, 0, 1.0]
PlotHistogramHovered = [255, 114, 0, 1.0]
TableHeaderBg = [198, 221, 249, 1.0]
TableBorderStrong = [145, 145, 163, 1.0]
TableBorderLight = [173, 173, 188, 1.0]
TableRowBg = [0, 0, 0, 0.0]
TableRowBgAlt = [76, 76, 76, 0.09]
TextSelectedBg = [66, 150, 249, 0.35]
DragDropTarget = [66, 150, 249, 0.95]
NavHighlight = [66, 150, 249, 0.8]
NavWindowingHighlight = [178, 178, 178, 0.7]
NavWindowingDimBg = [51, 51, 51, 0.2]
ModalWindowDimBg = [51, 51, 51, 0.35]

[extras]
AxisXColor = [255, 68, 68, 255]
AxisYColor = [68, 255, 68, 255]
AxisZColor = [68, 68, 255, 255]
